travis:
  secure:
    BINSTAR_TOKEN: DsB/5HyAMg85ajWr5KfYkmR3yDiMXyz+0RI5UX3KEt6hz9LMLU6FP1WAz/iY8jQHh0Ees/V3ysLW28eYCkHQ7B2DZ1xKabajw5YFYa+Gu5dohEQh5qLBmfBHjRp+Rqv0sd/UdgY2oK6+/wDIBAxdcLBhNcRzNk9+a7FSWn/ZGbf8WI8W/V3QEErP3dYr2hErj3PKoaACtDmyq20aIdGov5MFWbkFGExp0zAafeW95QXvIlaBKnyg6cUqCoW1wbxoP1ch6q3lC5V8YNESS9qvUJymImymrHLz2lWYFyZ7CO5NWnUz25blokXt5SjwiLFf7RIp4a8RWbVSjjajrkfulC55sEOiMbhwKpexBvM9xFflBw1RM2SNOOOfmQcppKKntXgWMmFye9E8SLaPP3DKNslxJisylKGQPtBrelcCwZ2gNDRp3PndKsc7CaaK+W//ju+V2EaQvvyKKMt4kOOig3JLnEItso/q/1Bnmk3OlJTmq9p3pKBk7pEWM638G2MKJ/dJroaDu7iVfY+KyW1oHtOkEMCmYu2EdVjOu/wwsYnSFiCiFh7h7UiAzUap68kNayux4lLsCr2BPn7gVCuT/vSbuH7TfyKptP5pjbCB9pprO9ptston945jZafXVogTY9zBJil2/nJvYCxhgMtRaHDWIAYq4V8SwgDpR3dcGtA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
